In [1]:
from giverny.turbulence_dataset import *
from giverny.turbulence_toolkit import *
import numpy as np
import pandas as pd
auth_token = 
#auth_token = 'edu.jhu.pha.turbulence.testing-201406'
dataset_title = 'mixing'
output_path = './giverny_output'

dataset = turb_dataset(dataset_title = dataset_title, output_path = output_path, auth_token = auth_token)

In [2]:
var = "velocity"
total_time  = 40.44
t0  = 0
dt = 0.04
n_tgt = total_time / dt + 1
n_tgt = int(n_tgt)
option = [total_time, dt]
times    = np.linspace(0.0, total_time, n_tgt)
spatial_method = "none"
temporal_method = "none"
spatial_op = "field"
option = [total_time, dt]

In [ ]:
nx, ny, nz = 9, 9,9
xs = np.linspace(0, 2*np.pi, nx)
ys = np.linspace(0, 2*np.pi, ny)
zs = np.linspace(0, 2*np.pi, nz)
points = np.array([axis.ravel() for axis in np.meshgrid(xs, ys, zs, indexing = 'ij')], dtype = np.float64).T
print(xs,ys,zs)
print(points)
arrays = []
raw = getData(dataset, 'velocity',t0,temporal_method, spatial_method, spatial_op, points, option)
raw = np.asarray(raw)                  
nt, *space_dims = raw.shape            
n_space = np.prod(space_dims)          

# reshape to (nt, n_space)
snapshots = (raw.reshape(nt, n_space)).T
print(snapshots.shape)
np.save('mixingdata5184.npy', snapshots)

[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531] [0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531] [0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
[[0.         0.         0.        ]
 [0.         0.         0.78539816]
 [0.         0.         1.57079633]
 ...
 [6.28318531 6.28318531 4.71238898]
 [6.28318531 6.28318531 5.49778714]
 [6.28318531 6.28318531 6.28318531]]

-----
getData is processing...


times completed (n = 1012) :   0%|          | 0/1012 [00:00<?, ?it/s]

In [ ]:
arrays = []
raw = getData(dataset, 'velocity',t0,temporal_method, spatial_method, spatial_op, points, option)
raw = np.asarray(raw)                  
nt, *space_dims = raw.shape            
n_space = np.prod(space_dims)          

snapshots = (raw.reshape(nt, n_space)).T
print(snapshots.shape)
np.save('.npy', snapshots)

In [ ]:
raw = np.asarray(raw)                 
nt, *space_dims = raw.shape            
n_space = np.prod(space_dims)          

# reshape to (nt, n_space)
snapshots = (raw.reshape(nt, n_space)).T

In [ ]:
print(snapshots.shape)

In [ ]:
np.save('.npy', snapshots)